---
title: 'RMarkdown:  In Class Assignment'
author: "Elizabeth Serrano"
date: "Data 2401"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE) ## this line makes all the code show! 
  ## and these lines are comments - anything behind a '#' doesn't run!
```


Reminder: There is a "Markdown Help" page available in RStudio. 


## In-class Activity, Markdown

Below the "Your work here" section header, do the following 3 things. To turn this in, knit the RMarkdown file, and zip and submit the html.  

1. Make a subsection called "Wise words". Put your favorite quote in a block quote. Add a functioning link to a website that provides more information about that quote.

## Wise words

> You do not find the happy life. You make it.

[link](https://everydaypower.com/short-inspirational-quotes/#:~:text=%E2%80%9CIf%20I%20cannot%20do%20great,%E2%80%9D%20%E2%80%93%20Martin%20Luther%20King%20Jr.&text=What%20is%20this%3F,-Report%20Ad)

2. Make a subsection called "My semester". Make a three column table of the current courses you are taking, with separate columns for course number (put those in __bold__), course title (put those in _italics_), and instructor name.

## My semester

|**Course Number**|*Course Title*| Instructor Name|
|:-------------------|:----------------------|:---------------|
| **22479**|*Intro to Computing with Python*| Joseph Kamto|
| **21352**|*Data Science I*| Katherine Anne Shoemaker |
|**21732**|*Discrete Mathematical Structures*| Mitsue Nakamura|
|**22319**| *Differential & Integral Calculus*| Sergly Koshkin|

3. Lastly, make subsection called "I recommend", and add some information about your favorite author or musician.

+ A _subsubheading_ with the name of the artist or author;    
+ An example of their writing or lyrics (formatted in a *plain code block*);   
+ A _list_ of things they have written or performed (remember to use the formatting markup for a list!).     

## I recommend

## The Midnight 
Lyrics from the song called River of Darkness. 


Note that you can click "Knit" as you go along to see what the final results are going to look like. **Once you're done, commit the changes and push the repo back to your assignment on GitHub!**
 
